GalacticDVDReact/Controllers/DVDManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GalacticDVDReact.EntityModels;

namespace GalacticDVDReact.Controllers
{
    public class DVDManageController : Controller
    {
        private GalacticDBEntities db = new GalacticDBEntities();

        // GET: DVDManage
        public ActionResult Index()
        {
            return View(db.DVDInfoes.ToList());
        }

        // GET: DVDManage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DVDInfo dVDInfo = db.DVDInfoes.Find(id);
            if (dVDInfo == null)
            {
                return HttpNotFound();
            }
            return View(dVDInfo);
        }

        // GET: DVDManage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DVDManage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DVDInfo dVDInfo, HttpPostedFileBase image1)
        {
            DVDInfo b1 = new DVDInfo();
            if (image1 != null)
            {
                dVDInfo.Image = new byte[image1.ContentLength];
                image1.InputStream.Read(dVDInfo.Image, 0, image1.ContentLength);
            }
            if (ModelState.IsValid)
            {
                db.DVDInfoes.Add(dVDInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dVDInfo);
        }

        // GET: DVDManage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DVDInfo dVDInfo = db.DVDInfoes.Find(id);
            if (dVDInfo == null)
            {
                return HttpNotFound();
            }
            return View(dVDInfo);
        }

        // POST: DVDManage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DvdId,Title,Description,Starring,Price,Genre,Image")] DVDInfo dVDInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dVDInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dVDInfo);
        }

        // GET: DVDManage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DVDInfo dVDInfo = db.DVDInfoes.Find(id);
            if (dVDInfo == null)
            {
                return HttpNotFound();
            }
            return View(dVDInfo);
        }

        // POST: DVDManage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DVDInfo dVDInfo = db.DVDInfoes.Find(id);
            db.DVDInfoes.Remove(dVDInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GalacticDVDReact/Controllers/GenreController.cs
using GalacticDVDReact.EntityModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using GalacticDVDReact.ViewModel;

using GalacticDVDRentals.ViewModel;
using System.IO;
using System.Drawing;

namespace GalacticDVDReact.Controllers
{
	public class GenreController : Controller
	{
		GalacticDBEntities db = new GalacticDBEntities();
		private IMapper _mapper;

		//Automapper config
		public GenreController()
		{
			_mapper = new AutoMapper.MapperConfiguration(cfg =>
			{
				cfg.CreateMap<DVDInfo, DvdInfoModel>()
					.ForSourceMember(src => src.Starring, opts => opts.Ignore())
					.ForSourceMember(src => src.Price, opts => opts.Ignore());



				cfg.CreateMap<DVDInfo, DetailView>();
				
			}).CreateMapper();
		}


		//Passing JSON to react components in Movie.jsx
		public JsonResult GetDvdInfoForGenre(string genre)
		{
			using (var context = new GalacticDBEntities())
			{
				//Mapper
				var moviesForGenre = context.DVDInfoes.Where(a => a.Genre == genre).ToList();
				var data = _mapper.Map<IEnumerable<DVDInfo>, IEnumerable<DvdInfoModel>>(moviesForGenre);
				
				//JSON result
				return new JsonResult { Data = data, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
			}
		}
		/// </summary>

		//Action View Result
		public ActionResult Index(string genrepass1)
		{
			return View(new  GenreModel{ Genre = genrepass1} );
			
		}

		public JsonResult getDetailInfoForDetails(int newId)
		{

			var test2 = db.DVDInfoes.FirstOrDefault(a => a.DvdId == newId);
			var movieDetail = _mapper.Map<DetailView>(test2);
			return new JsonResult { Data = movieDetail, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

		}

		public ActionResult Details (int id)
		{
			return View(new DetailView { DvdId = id});

		}


		[HttpGet]
		public ActionResult Image(int id)
		{
			using (var context = new GalacticDBEntities())
			{
				var image = context.DVDInfoes.First(info => info.DvdId == id).Image;
				return new FileStreamResult(new MemoryStream(image), "image/png");
			}
		}
		[HttpGet]
		public JsonResult DropDownList()
		{

			using (var lookup = new GalacticDBEntities())
			{
				var genreNames = lookup
					.DVDInfoes
					.Select(a => a.Genre)
					.Distinct()
					.OrderBy(s => s)
					.ToList();

				//List<string> dropdownlist = new List<string>();
				//var count = "";
				//foreach (var item in genreNames)
				//{
				//	if (count != item)
				//	{
				//		count = item;
				//		dropdownlist.Add(count);
				//	}
				//}

				return new JsonResult { Data = genreNames, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

			}




		}

	}




	}
	

GalacticDVDReact/Controllers/HomeController.cs
using AutoMapper;
using GalacticDVDReact.EntityModels;
using GalacticDVDReact.ViewModel;
using GalacticDVDRentals.ViewModel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GalacticDVDReact.Controllers
{
    public class HomeController : Controller
    {
        GalacticDBEntities db = new GalacticDBEntities();
        private IMapper _mapper;
        public HomeController()
        {

            _mapper = new AutoMapper.MapperConfiguration(cfg =>
            {
                cfg.CreateMap<DVDInfo, GenreModel>()
                    .ForSourceMember(src => src.Starring, opts => opts.Ignore())
                    .ForSourceMember(src => src.Price, opts => opts.Ignore());



                cfg.CreateMap<DVDInfo, DetailView>();

            }).CreateMapper();
        }


        // GET: Home
        public ActionResult Index()
        {

            GenreTextGet();
            return View(new GenreModel());
        }

        public ActionResult GenreTextGet()
        {

            using (var lookup = new GalacticDBEntities())
            {
                var genreList = lookup
                    .DVDInfoes
                    .Select(a => a.Genre)
                    .Distinct()
                    .OrderBy(s => s)
                    .ToList();

                ViewBag.genreListing = genreList;
                return View();

            }




        }
    }
    
}

GalacticDVDReact/Views/DVDManage/Create.cshtml
@model GalacticDVDReact.EntityModels.DVDInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "DVDManage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DVDInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Starring, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Starring, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Starring, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <input type="file" id="image1" name="image1" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GalacticDVDReact/Views/DVDManage/Delete.cshtml
@model GalacticDVDReact.EntityModels.DVDInfo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DVDInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Starring)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Starring)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GalacticDVDReact/Views/DVDManage/Details.cshtml
@model GalacticDVDReact.EntityModels.DVDInfo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DVDInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Starring)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Starring)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DvdId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GalacticDVDReact/Views/DVDManage/Edit.cshtml
@model GalacticDVDReact.EntityModels.DVDInfo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DVDInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DvdId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Starring, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Starring, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Starring, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GalacticDVDReact/Views/DVDManage/Index.cshtml
@model IEnumerable<GalacticDVDReact.EntityModels.DVDInfo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Starring)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Starring)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
          @{    var base64 = Convert.ToBase64String(item.Image);
              var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
          }
          <img src='@imgsrc' style="max-height:100px;max-width:100px;" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DvdId }) |
            @Html.ActionLink("Details", "Details", new { id=item.DvdId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DvdId })
        </td>
    </tr>
}

</table>

GalacticDVDReact/Views/Genre/Details.cshtml
@model GalacticDVDReact.ViewModel.DetailView

@{
    ViewBag.Title = "Index";
}


<div id="detailDiv" class="flexcontainer-genre"></div>
<script src="@Url.Content("~/jsx/Detail.jsx")"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />


<script type="text/babel">
  ReactDOM.render(
  <DetailsRender dataUrl="/Genre/getDetailInfoForDetails?newId=@Model.DvdId" />,
  document.getElementById('detailDiv')
  );
</script>

GalacticDVDReact/Views/Genre/Index.cshtml
@model GalacticDVDRentals.ViewModel.GenreModel

@{
    ViewBag.Title = "Index";
}



<link href="~/Content/Site.css" rel="stylesheet" />
<div id="container1"></div>
<script src="@Url.Content("~/jsx/dropdown.jsx")"></script>

<div>
  <h2>@Model.Genre</h2>
</div>
<div id="griddata" class="flexcontainer-genre"></div>
<script src="@Url.Content("~/jsx/Genre.jsx")"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.6/react-dom.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />

@{ 
    var genre = Model.Genre;
    var text =Html.Action("GetDvdInfoForGenre", "Genre", genre);

}

<script type="text/babel">
  

  ReactDOM.render(
  <MovieGridTable dataUrl="/Genre/GetDvdInfoForGenre?genre=@Model.Genre" />,
  document.getElementById('griddata')
  );

  ReactDOM.render(
  <DropDown value="@Model.Genre" dataUrl2="/Genre/DropDownList" />,
  document.getElementById('container1')
  );
</script>

<!--$.getJSON("/Genre/GetDvdInfoForGenre?Model.Genre", function(data) {
 var GenreItems = data
      })
      // en dan die GenreItems add by die ReactDOM by "dataUrl", en "GenreItems in my Genre.jsx roep in die function"

      //Of die data van die controller "GetDvdInfoForGenre" hier bo stoor as Raw Json?
      // iets soos "Html.Raw(Json.Encode(....))" <-- het dit op internet gelees

      //Ek kan my net voorstel dat ek n AJAX call hier moet doen, maar dan moet ek die hele Genre.jsx oordoen reg?
      // Sit vas want hoe meer ek uitredeneer hoe langer word my code....
      -->

GalacticDVDReact/Views/Home/Index.cshtml
@model GalacticDVDRentals.ViewModel.GenreModel

@{
    ViewBag.Title = "Index";
}



<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/JavaScript.js"></script>
<div>
    <img src="~/images/galactic.png" class="header-img" />
</div>
<div style="text-align:center; margin-top:50px;">
    <p>
        <h1><b>Welcome to Galatic DVD Rentals!</b></h1><br /><br />


        <h4>
            We have the latest and greatest in home entertainment at low, low prices.<br />
            Browse our full catalog of DVDs, organised by category.<br />
            You can book by calling us on 021 555 1234,<br />
            or emailing us at
        </h4> <a href="mailto:booking@galacticdvdrentals.com">
    <p style="font-size:22px">booking@galacticdvdrentals.com</p></a>
    </p>
</div>
<div class="flexcontainer">


    @{
        foreach (var item in ViewBag.genreListing)
        {
            <div class="flex-item" id="texts">@Html.ActionLink((string)@item, "Index", "Genre", new RouteValueDictionary(new { genrepass1 = (string)@item }), null)</div>
        }
    }



</div>

GalacticDVDReact/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Galactic DVD Rentals</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.2/react.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.2/react-dom.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.7.1/remarkable.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Galactic DVD Rentals", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Galactic DVD Rentals</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>